### ISSUE TITLE
Logic Issues

### ISSUE THREAD

**Issue by gollop** [BashPrime/metroid-prime-randomizer#41] opened 2020-09-08 20:57 UTC
https://github.com/BashPrime/metroid-prime-randomizer/blob/support/2.x/src/electron/models/prime/regions/chozoRuins.ts#L45
No exit to Vault from Main Plaza Locked Door Ledge.

https://github.com/BashPrime/metroid-prime-randomizer/blob/support/2.x/src/electron/models/prime/regions/chozoRuins.ts#L491
Reflecting Pool assumes requirements are always needed for climbing the room, but you can take an elevator to the room and avoid having to climb it.

https://github.com/BashPrime/metroid-prime-randomizer/blob/support/2.x/src/electron/models/prime/regions/chozoRuins.ts#L190
If the crossMagmaPoolSuitless is enabled, crossing Magma Pool will always require 2 energy tanks and Space Jump.

https://github.com/BashPrime/metroid-prime-randomizer/blob/support/2.x/src/electron/models/prime/regions/chozoRuins.ts#L321
Sunchamber -> Arboretum does not check if the ibj trick is enabled.

https://github.com/BashPrime/metroid-prime-randomizer/blob/support/2.x/src/electron/models/prime/regions/tallonOverworld.ts#L170
Great Tree Chamber does not require ice beam.

https://github.com/BashPrime/metroid-prime-randomizer/blob/support/2.x/src/electron/models/prime/regions/tallonOverworld.ts#L192
Thermal shouldn't be required if the remove thermal visor requirements trick is on.

https://github.com/BashPrime/metroid-prime-randomizer/blob/support/2.x/src/electron/models/prime/regions/tallonOverworld.ts#L263
Doesn't require Space Jump

https://github.com/BashPrime/metroid-prime-randomizer/blob/support/2.x/src/electron/models/prime/regions/magmoorCaverns.ts#L27
Item can also be gotten with Charge Beam instead of missiles.

**Comment by BashPrime** [comment] 2020-09-08 22:17
> No exit to Vault from Main Plaza Locked Door Ledge.

This was an intentional design choice. It's probably worth adding an exit if the door is enabled and if "Main Plaza Items with only Space Jump" is enabled.

> Reflecting Pool assumes requirements are always needed for climbing the room, but you can take an elevator to the room and avoid having to climb it.

Good point. It's worth splitting this region into an upper and lower section. Thanks.

> If the crossMagmaPoolSuitless is enabled, crossing Magma Pool will always require 2 energy tanks and Space Jump.

That is by design and explained in the trick description, unless you're referring to that strat I've heard about where you can use collision to avoid needing to scan dash. Can you please elaborate?

> Great Tree Chamber does not require ice beam.
> Thermal shouldn't be required if the remove thermal visor requirements trick is on.

Great catch. Thank you.

> Doesn't require Space Jump

This was done to enforce space jump requirements for Great Tree Hall, but I can refactor this.

> Item can also be gotten with Charge Beam instead of missiles.

I wasn't aware of this actually! Thanks.

**Comment by BashPrime** [comment] 2020-09-08 22:18
> Sunchamber -> Arboretum does not check if the ibj trick is enabled.

I believe I intentionally left that out but I'll revisit this.

**Comment by BashPrime** [comment] 2020-09-08 22:21
Thanks for clarifying about the Magma Pool issue. That will be fixed.

**Comment by BashPrime** [comment] 2020-09-09 06:28
Logic fixes have been applied.

**Closed by BashPrime** 2020-09-09 06:28 UTC
